---
name: 'Run tests'

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
      OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: |
          mkdir data && touch data/db.sqlite
          npm install knex -g
          knex migrate:latest -x ts
      - run: npm run test